# Generated by Django 5.0.4 on 2024-05-07 13:24

import django.db.models.deletion
import scanpipe.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0056_alter_run_scancodeio_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhooksubscription",
            name="delivery_error",
        ),
        migrations.RemoveField(
            model_name="webhooksubscription",
            name="response_status_code",
        ),
        migrations.RemoveField(
            model_name="webhooksubscription",
            name="response_text",
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
                (
                    "response_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("response_text", models.TextField(blank=True)),
                ("delivery_error", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="scanpipe.project",
                    ),
                ),
                (
                    "webhook_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="scanpipe.webhooksubscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(scanpipe.models.UpdateMixin, models.Model),
        ),
    ]
